name: ItemEjector
main: me.loidsemus.itemejector.ItemEjector
version: @version@
author: loidsemus
api-version: 1.13

commands:
  itemejector:
    description: Main ItemEjector command
    aliases: [ie, iejector, autoeject, autoejector]

permissions:
  itemejector.use:
    description: Use ItemEjector
    default: true
  itemejector.admin:
    description: ItemEjector admin commands, e.g reload
    default: op
    children:
      itemejector.use: true
  itemejector.*:
    description: Access to all ItemEjector commands
    default: op
    children:
      itemejector.admin: true
      itemejector.use: true